declare module 'react-table';
declare module 'react-apexcharts';
declare module 'react-facebook-login/dist/facebook-login-render-props';
declare module 'lodash';
declare module '@ckeditor/ckeditor5-react';
declare module '@ckeditor/ckeditor5-build-classic';
declare module 'xlsx';
declare module 'papaparse';
declare module 'html2pdf.js';
